# Site settings
title: Max Bartlett's Blog
description: "Computer Science, Math, and anything else"
url: "maxbartlett.net/emerald"
author:
  name: "Max Bartlett"
  email: "maxwellmbartlett@gmail.com"
  url: "www.maxbartlett.net"

# Build settings
baseurl: /blog/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
