# Site settings
title: myDNA | A site to enable you to analyse your DNA
description: "A blog about DNA analysis, build with Jekyll."
url: "https://juliaht.github.io/myDNA/"


# Build settings
baseurl: /myDNA/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
