# Site settings
title: Panama Papers
description: "Where does the money come from ?"
#url: "http://www.jacoporabolini.com/emerald"
author:
  name: "Adrien Ruault, Guillaume Mollard, Hadrien Marcellin"
  #email: "hello@jacoporabolini.com"
  url: "https://hadrienmarcellin.github.io/ada_jekyll_page/"

# Build settings
baseurl: /ada_jekyll_page # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
