# Site settings
title: A Developer Marketing Blog by Jesse Williams
description: "A simple blog focused on the complexity of developer marketing, developer relations, building open source communities, and how to take developer focused products to market."
url: "http://jesse-williams.com"
author:
  name: "Jesse Williams"
  email: "jessewilliams.r@gmail.com"
  url: "http://jesse-williams.com"
logo: /img/jesse-williams-logo.png

# Build settings
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"



# Custom variables
version: "1.1.2"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap


# Options
custom_header: false
custom_nav_footer: false
reverse: false


